# Generated by Django 2.0 on 2017-12-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={'verbose_name_plural': 'Catalog categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_us',
            new_name='price',
        ),
    ]
