# Generated by Django 2.0 on 2017-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171219_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
