# Generated by Django 2.0 on 2017-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171220_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
